# Generated by Django 4.2.7 on 2023-11-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Booking'},
        ),
    ]
