# Generated by Django 4.2.7 on 2023-11-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restuarant', '0002_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Booking'},
        ),
    ]
